kind: Pod
apiVersion: v1
metadata:
  name: echo-foo
  labels:
    app: echo-app
spec:
  containers:
  - name: app
    image: hashicorp/http-echo:0.2.3
    args:
    - "-text=foo"
---
kind: Pod
apiVersion: v1
metadata:
  name: echo-bar
  labels:
    app: echo-app
spec:
  containers:
  - name: app
    image: hashicorp/http-echo:0.2.3
    args:
    - "-text=bar"
---
kind: Service
apiVersion: v1
metadata:
  name: echo
spec:
  type: LoadBalancer
  selector:
    app: echo-app
  ports:
  # Default port used by the image
  - port: 5678
