apiVersion: v1
kind: Pod
metadata:
  name: testserver
spec:
  containers:
  - name: agnhost
    image: registry.k8s.io/e2e-test-images/agnhost:2.39
    args:
    - netexec
    - --udp-port=80
    ports:
    - containerPort: 80

