apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: kuber-learn--simple-service-1
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: dev.local/kuber_learn__simple_service_1:v0
          imagePullPolicy: Never
          ports:
          - name: http1 # or h2c for HTTP2, both work
            # knative exposes this port to service containers via $PORT env var.
            # If we omit "ports", then it sets $PORT=8080 by default.
            containerPort: 5001
