apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: kuber-learn--simple-service-1
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: knative.registry.svc.cluster.local/kuber_learn__simple_service_1:v0
        #- image: k8s.gcr.io/echoserver:1.10  # it doesn't work because it doesn't use $PORT
        #- image: gcr.io/knative-samples/helloworld-go
        #- image: knative.registry.svc.cluster.local/helloworld-go
