apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: kuber-learn--simple-service-1
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: dev.local/kuber_learn__simple_service_1:v0
          imagePullPolicy: Never

