apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: echo
  name: echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  strategy: {}
  template:
    metadata:
      labels:
        app: echo
    spec:
      # Let's pretend that this service takes some time to start
      initContainers:
      - name: init
        image: busybox
        command:
        - 'sh'
        - '-c'
        - 'rm /echo/log; echo $(date +%s): SERVICE starting >> /echo/log; sleep 30; echo $(date +%s): SERVICE started >> /echo/log;'
        volumeMounts:
        - mountPath: /echo
          name: echo-log
      containers:
      - image: hashicorp/http-echo:0.2.3
        name: echo
        args: ["-text=Hello world!"]
        ports:
        - name: http
          containerPort: 5678
          protocol: TCP
      volumes:
      - name: echo-log
        hostPath:
          path: /tmp/echo
---
apiVersion: v1
kind: Service
metadata:
  name: echo-service
spec:
  type: NodePort
  selector:
    app: echo
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-client
  template:
    metadata:
      labels:
        app: echo-client
    spec:
      # Main container will not be started before all init containes finishes
      # Use nc in init container for waiting for service to be ready
      initContainers:
      - name: init
        image: busybox
        command:
        - 'sh'
        - '-c'
        - 'until nc -vz echo-service 80; do echo $(date +%s): CLIENT waiting for service... >> /echo/log; sleep 5; done;'
        volumeMounts:
        - mountPath: /echo
          name: echo-log
      containers:
      - name: main
        image: alpine/curl
        command:
        - 'sh'
        - '-c'
        - 'echo $(date +%s): CLIENT $() >> /echo/log; curl echo-service >> /echo/log;'
        volumeMounts:
        - mountPath: /echo
          name: echo-log
      volumes:
      - name: echo-log
        hostPath:
          path: /tmp/echo
