apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-ping-go-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-ping-go
  template:
    metadata:
      labels:
        app: grpc-ping-go
    spec:
      containers:
        - name: grpc-ping-go
          image: dev.local/grpc-ping-go
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-ping-go-service
spec:
  type: NodePort
  selector:
    app: grpc-ping-go
  ports:
    - protocol: TCP
      port: 8080
