apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-py
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: dev.local/helloworld_py:v0
          env:
            - name: TARGET
              value: "Python Sample v0"
