apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-greeter-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-greeter
  template: # pod template
    metadata:
      labels:
        app: grpc-greeter
    spec:
      containers:
        - name: grpc-greeter
          image: grpc_greeter:v0
          imagePullPolicy: Never
          ports:
            - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-greeter-service
spec:
  type: NodePort
  selector:
    app: grpc-greeter
  ports:
    - protocol: TCP
      port: 50051
