apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-new-service-v0-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-new-service-v0
  template:
    metadata:
      labels:
        app: my-new-service-v0
    spec:
      containers:
        - name: my-new-image-v0
          image: knative.registry.svc.cluster.local/my-new-image:v0
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: my-new-service-v0-service
spec:
  type: NodePort
  selector:
    app: my-new-service-v0
  ports:
    - protocol: TCP
      port: 5000
