apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuber-learn--simple-service-1-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      # the deployment will handle pods with this label
      app: kuber-learn--simple-service-1
  template: # pod template
    metadata:
      labels:
        # make a label to allow deployment and service to find these pods
        app: kuber-learn--simple-service-1
    spec:
      containers:
        - name: kuber-learn--simple-service-1
          image: kuber_learn__simple_service_1:v0
          # prevent kubernetes from downloading image from somewhere
          # without this there will be ErrImagePull status of pods
          # but it only happens with kvm minikube driver
          # with virtualbox driver all works ok with and without this option
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: kuber-learn--simple-service-1-service
spec:
  type: NodePort
  selector:
    # service will select pods with this label
    app: kuber-learn--simple-service-1
  ports:
    - protocol: TCP
      port: 5000
