apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dp1
spec:
  selector:
    matchLabels:
      app: dp1
  template:
    metadata:
      labels:
        app: dp1
    spec:
      containers:
        - name: dp1
          image: device-plugin-1:0
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: dp
              mountPath: /var/lib/kubelet/device-plugins
      volumes:
        - name: dp
          hostPath:
            path: /var/lib/kubelet/device-plugins
            type: DirectoryOrCreate
